/**
 * Airbooks Design System — Style Dictionary v5 config
 *
 * Builds two outputs:
 *   1. dist/tokens.css   — All semantic + component tokens as CSS custom
 *                          properties on :root. References preserved as
 *                          var(--token-name) so the alias graph stays
 *                          intact in the output.
 *   2. dist/tokens.json  — Nested JSON tree, references resolved.
 *                          For Framer mirror, tooling, and documentation.
 *
 * Source files live under `tokens/`, tiered primitive → semantic → component.
 * Style Dictionary merges all source JSON files into one tree at build time.
 *
 * Run:    npm run tokens
 * Or:     npx style-dictionary build
 */

export default {
  source: ['tokens/**/*.json'],

  // DTCG token format ($value, $type, $description) is detected automatically
  // when source tokens use that shape — no flag needed in Style Dictionary v5.

  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
            // Emit a header acknowledging the source.
            fileHeader: () => [
              'Airbooks Design System — token output',
              'Generated from tokens/**/*.json by Style Dictionary v5.',
              'Do not edit this file. Edit the source JSON and re-run `npm run tokens`.'
            ]
          }
        }
      ]
    },

    json: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.json',
          format: 'json/nested'
        }
      ]
    }
  }
};
