import StyleDictionary from 'style-dictionary';

// Emit DS tokens as CSS custom properties under a `--ds-*` namespace so they
// never collide with Tailwind v4's reserved `--color-*` / `--text-*` / `--spacing-*`
// theme namespaces. app/globals.css maps the Tailwind theme onto these vars.

const toName = (path) => 'ds-' + path.join('-');

function cssValue(token) {
  const type = token.$type ?? token.type;
  const val = token.$value ?? token.value;
  if (type === 'fontFamily') {
    const arr = Array.isArray(val) ? val : [val];
    return arr.map((f) => (/\s/.test(f) ? `'${f}'` : f)).join(', ');
  }
  if (type === 'shadow') {
    const list = Array.isArray(val) ? val : [val];
    return list
      .map((s) => `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`)
      .join(', ');
  }
  return String(val);
}

// Give every token a unique name from its full path so SD's internal
// collision check (which otherwise sees bare leaf keys like "50") stays quiet.
StyleDictionary.registerTransform({
  name: 'name/ds-path',
  type: 'name',
  transform: (token) => toName(token.path),
});

StyleDictionary.registerFormat({
  name: 'css/ds-vars',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (t) => `  --${toName(t.path)}: ${cssValue(t)};`
    );
    return (
      '/* AUTO-GENERATED by Style Dictionary — do not edit.\n' +
      '   Source of truth: tokens/src/*.json. Regenerate with `npm run tokens`. */\n' +
      ':root {\n' +
      lines.join('\n') +
      '\n}\n'
    );
  },
});

export default {
  source: ['tokens/src/**/*.json'],
  // No transforms: we resolve references and format composites in the format
  // above, keeping authored values (hex, px, unitless) verbatim.
  platforms: {
    css: {
      transforms: ['name/ds-path'],
      buildPath: 'app/',
      files: [
        {
          destination: 'tokens.generated.css',
          format: 'css/ds-vars',
          options: { usesDtcg: true, outputReferences: false },
        },
      ],
      options: { usesDtcg: true },
    },
  },
};
